#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path
from typing import Any

from media_utils import ensure_dir

AUTH_COOKIE_NAMES = {
    "SID",
    "HSID",
    "SSID",
    "APISID",
    "SAPISID",
    "__Secure-1PSID",
    "__Secure-3PSID",
    "__Secure-1PSIDTS",
    "__Secure-3PSIDTS",
    "__Secure-1PSIDCC",
    "__Secure-3PSIDCC",
    "LOGIN_INFO",
}

COOKIE_DOMAIN_SUFFIXES = (
    "youtube.com",
    "google.com",
    "googleusercontent.com",
    "googlevideo.com",
    "ytimg.com",
    "gstatic.com",
)


def is_relevant_cookie(cookie: dict[str, Any]) -> bool:
    domain = str(cookie.get("domain") or "").lstrip(".").lower()
    return any(domain == suffix or domain.endswith(f".{suffix}") for suffix in COOKIE_DOMAIN_SUFFIXES)


def has_youtube_auth(cookies: list[dict[str, Any]]) -> bool:
    for cookie in cookies:
        if not is_relevant_cookie(cookie):
            continue
        if str(cookie.get("name") or "") in AUTH_COOKIE_NAMES:
            return True
    return False


def netscape_bool(value: bool) -> str:
    return "TRUE" if value else "FALSE"


def clean_cookie_field(value: Any) -> str:
    return str(value or "").replace("\t", " ").replace("\r", "").replace("\n", "")


def cookie_domain_for_netscape(cookie: dict[str, Any]) -> tuple[str, bool]:
    domain = clean_cookie_field(cookie.get("domain"))
    include_subdomains = domain.startswith(".")
    if not domain:
        domain = ".youtube.com"
        include_subdomains = True
    return domain, include_subdomains


def write_netscape_cookies(cookies: list[dict[str, Any]], output_path: Path) -> int:
    ensure_dir(output_path.parent)
    relevant = [cookie for cookie in cookies if is_relevant_cookie(cookie)]
    relevant.sort(key=lambda item: (str(item.get("domain") or ""), str(item.get("path") or ""), str(item.get("name") or "")))

    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by clipping-skill. Contains private session cookies; do not share.",
    ]
    for cookie in relevant:
        domain, include_subdomains = cookie_domain_for_netscape(cookie)
        if bool(cookie.get("httpOnly")) and not domain.startswith("#HttpOnly_"):
            domain = f"#HttpOnly_{domain}"
        expires = cookie.get("expires")
        try:
            expires_int = int(expires)
        except (TypeError, ValueError):
            expires_int = 0
        if expires_int < 0:
            expires_int = 0
        fields = [
            domain,
            netscape_bool(include_subdomains),
            clean_cookie_field(cookie.get("path") or "/"),
            netscape_bool(bool(cookie.get("secure"))),
            str(expires_int),
            clean_cookie_field(cookie.get("name")),
            clean_cookie_field(cookie.get("value")),
        ]
        lines.append("\t".join(fields))

    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    try:
        output_path.chmod(0o600)
    except OSError:
        pass
    return len(relevant)


def wait_for_auth(context: Any, timeout_sec: int) -> list[dict[str, Any]]:
    start = time.monotonic()
    last_cookies: list[dict[str, Any]] = []
    while True:
        last_cookies = context.cookies()
        if has_youtube_auth(last_cookies):
            time.sleep(2)
            return context.cookies()
        if time.monotonic() - start >= timeout_sec:
            return last_cookies
        time.sleep(2)


def main() -> int:
    parser = argparse.ArgumentParser(description="Open a managed YouTube login browser and export cookies for yt-dlp.")
    parser.add_argument("--profile-dir", required=True, help="Persistent browser profile directory owned by this skill.")
    parser.add_argument("--cookies-out", required=True, help="Netscape cookies.txt output path for yt-dlp.")
    parser.add_argument("--timeout", type=int, default=900, help="Seconds to wait for the user to finish YouTube login.")
    parser.add_argument(
        "--browser-channel",
        help="Optional Playwright browser channel, e.g. chrome or msedge. Defaults to bundled Chromium.",
    )
    parser.add_argument("--headless", action="store_true", help="Run headless. Only useful for an existing profile.")
    args = parser.parse_args()

    try:
        from playwright.sync_api import Error as PlaywrightError
        from playwright.sync_api import sync_playwright
    except ImportError:
        raise SystemExit("Playwright is not installed. Run: .venv/bin/pip install -r requirements.txt")

    profile_dir = ensure_dir(Path(args.profile_dir).expanduser())
    cookies_out = Path(args.cookies_out).expanduser()
    launch_options: dict[str, Any] = {
        "headless": args.headless,
        "viewport": {"width": 1320, "height": 900},
        "args": [
            "--disable-blink-features=AutomationControlled",
            "--no-first-run",
            "--no-default-browser-check",
        ],
    }
    if args.browser_channel:
        launch_options["channel"] = args.browser_channel

    print("Opening managed YouTube login browser.", flush=True)
    print("Sign in to YouTube in that window. This script exits automatically after auth cookies appear.", flush=True)

    try:
        with sync_playwright() as playwright:
            context = playwright.chromium.launch_persistent_context(str(profile_dir), **launch_options)
            page = context.pages[0] if context.pages else context.new_page()
            page.goto("https://www.youtube.com/", wait_until="domcontentloaded", timeout=60000)
            cookies = wait_for_auth(context, args.timeout)
            cookie_count = write_netscape_cookies(cookies, cookies_out)
            authed = has_youtube_auth(cookies)
            context.close()
    except PlaywrightError as exc:
        raise SystemExit(f"Managed YouTube auth browser failed: {exc}") from exc

    if not authed:
        print(f"Wrote {cookie_count} YouTube/Google cookies, but no signed-in YouTube auth cookie was detected.", flush=True)
        return 2

    print(f"Wrote {cookie_count} YouTube/Google cookies to {cookies_out}.", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
